import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import HomeLayout from '@/components/layouts/HomeLayout'
import Link from 'next/link'
import axios from 'axios'
import { useRouter } from 'next/router'

export default function Home() {
  const [subjects, setSubjects] = useState('')
  const router = useRouter()
  useEffect(() => {
    try{
      axios.get(process.env.NEXT_PUBLIC_API_URI+'/subject').then((res)=>{
      setSubjects(res.data)
     }
      )
}
catch(err){
    console.log(err)
  }
}, [])

console.log('env',process.env.NEXT_PUBLIC_API_URI)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeLayout>
        <div className='subjectDiv container'>
          {/* <h1>Subjects</h1> */}
        {subjects && subjects?.map((subject,i)=>(
      <button className='subjectBtn' onClick={()=>router.push({ pathname: '/question', 
      query: { id: subject.subject }})} key={i}>{subject.subject}</button>
      ))
    }
    </div>
      </HomeLayout>
    </>
  )
}
